### ISSUE TITLE
Support accepted_values for tests

### ISSUE THREAD

**Issue by gilcrest** [gilcrest/dbt-cue#1]
Tests should be able to have accepted_values, like below:

```yml
tests:
  - accepted_values:
    values: ['placed', 'shipped', 'completed', 'returned']
```
