### ISSUE TITLE
Allow for accepted _values of any type

### ISSUE THREAD

**Issue by gilcrest** [gilcrest/dbt-cue#2]
```yml
version: 2

models:
  - name: orders
    columns:
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'returned']

      - name: status_id
        tests:
          - accepted_values:
              values: [1, 2, 3, 4]
              quote: false
```
